steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull gcr.io/$PROJECT_ID/$REPO_NAME:latest || exit 0
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:latest"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "beta"
      - "run"
      - "deploy"
      - "$REPO_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--add-cloudsql-instances"
      - "$_DB_INSTANCE_NAME"
      - "--set-env-vars"
      - 'INSTANCE-CONNECTION-NAME=$_DB_INSTANCE_NAME'
      - "--set-env-vars"
      - "DATABASE_URL=$_DATABASE_URL"
      - "--allow-unauthenticated"
images: ["gcr.io/$PROJECT_ID/$REPO_NAME:latest"]
timeout: 2000s
