steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - "--destination=gcr.io/$PROJECT_ID/$REPO_NAME:latest"
      - "--cache=true"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "beta"
      - "run"
      - "deploy"
      - "$REPO_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:latest"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--add-cloudsql-instances"
      - "$_DB_INSTANCE_NAME"
      - "--set-env-vars"
      - 'INSTANCE-CONNECTION-NAME=$_DB_INSTANCE_NAME'
      - "--set-env-vars"
      - "DATABASE_URL=$_DATABASE_URL"
      - "--set-env-vars"
      - "ALLOWED_ORIGIN=$_ALLOWED_ORIGIN"
      - "--set-env-vars"
      - "GRAPHQL_URL=$_GRAPHQL_URL"
      - "--set-env-vars"
      - "GRAPHIQL_ORIGIN=$_GRAPHIQL_ORIGIN"
      - "--allow-unauthenticated"
options:
  machineType: N1_HIGHCPU_8
