steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - "--destination=gcr.io/$PROJECT_ID/$REPO_NAME:latest"
      - "--cache=true"
      - "--cache-ttl=24h"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "beta"
      - "run"
      - "deploy"
      - "$REPO_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:latest"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--add-cloudsql-instances"
      - "$_DB_INSTANCE_NAME"
      - "--set-env-vars"
      - 'INSTANCE-CONNECTION-NAME=$_DB_INSTANCE_NAME'
      - "--set-env-vars"
      - "DATABASE_URL=$_DATABASE_URL"
      - "--allow-unauthenticated"
timeout: 3000s
