version: '3'
services:
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgresql-webapp-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
     - LC_COLLATE=C
     - LC_CTYPE=C
     - LC_MESSAGES=C
     - LC_MONETARY=C
     - LC_NUMERIC=C
     - LC_TIME=C
volumes:
  postgresql-webapp-data:

